version: '3.6'
services:

  nginx:
    image: nginx:1.7.7
    container_name: nginx
    restart: always
    networks:
      - frontend
    ports:
      - 8080:80
    volumes:
      - ${NGINX_DEFAULT_CONF:-./default.conf}:/etc/nginx/conf.d/default.conf

  orthanc:
    image: orthancteam/orthanc:24.8.1
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - frontend
      - backend
    #    ports:
    #      - ${ORTHANC_DICOM_PORT:-4242}:4242
    #      - ${ORTHANC_HTTP_PORT:-8042}:8042
    volumes:
      - ${ORTHANC_CONFIG:-./orthanc.json}:/etc/orthanc/orthanc.json:ro
      - ../:/python
      - ./venv:/tmp/venv
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc
      - ORTHANC_PYTHON_SCRIPTS_YAML=${ORTHANC_PYTHON_SCRIPTS_YAML:-/python/example.yml}

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

networks:
  frontend:
  backend:
